[2025-05-20T10:07:15.407+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-20T10:07:15.456+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: merge_sources_pipeline.flight_extraction scheduled__2025-04-01T00:00:00+00:00 [queued]>
[2025-05-20T10:07:15.480+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: merge_sources_pipeline.flight_extraction scheduled__2025-04-01T00:00:00+00:00 [queued]>
[2025-05-20T10:07:15.482+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-05-20T10:07:15.518+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): flight_extraction> on 2025-04-01 00:00:00+00:00
[2025-05-20T10:07:15.549+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=175) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-20T10:07:15.554+0000] {standard_task_runner.py:72} INFO - Started process 187 to run task
[2025-05-20T10:07:15.563+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'merge_sources_pipeline', 'flight_extraction', 'scheduled__2025-04-01T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/inference_dag.py', '--cfg-path', '/tmp/tmpt90j6lga']
[2025-05-20T10:07:15.569+0000] {standard_task_runner.py:105} INFO - Job 16: Subtask flight_extraction
[2025-05-20T10:07:15.742+0000] {task_command.py:467} INFO - Running <TaskInstance: merge_sources_pipeline.flight_extraction scheduled__2025-04-01T00:00:00+00:00 [running]> on host f48b776a3d9f
[2025-05-20T10:07:15.963+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='merge_sources_pipeline' AIRFLOW_CTX_TASK_ID='flight_extraction' AIRFLOW_CTX_EXECUTION_DATE='2025-04-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-01T00:00:00+00:00'
[2025-05-20T10:07:15.966+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-20T10:07:15.989+0000] {python.py:240} INFO - Done. Returned value was: [{'flight_id': 'FLT000', 'aircraft_df_type': 'B777', 'origin': 'LHR', 'destination': 'DXB', 'Date': '2025-01-19', 'Take-off Time (UTC)': '06:40', 'CO2_emission': 1593.82}, {'flight_id': 'FLT001', 'aircraft_df_type': 'B777', 'origin': 'DXB', 'destination': 'JFK', 'Date': '2025-01-13', 'Take-off Time (UTC)': '13:19', 'CO2_emission': 1284.75}, {'flight_id': 'FLT002', 'aircraft_df_type': 'A320', 'origin': 'LHR', 'destination': 'JFK', 'Date': '2025-01-12', 'Take-off Time (UTC)': '15:44', 'CO2_emission': 2313.58}, {'flight_id': 'FLT003', 'aircraft_df_type': 'B777', 'origin': 'DXB', 'destination': 'CDG', 'Date': '2025-01-12', 'Take-off Time (UTC)': '18:18', 'CO2_emission': 1264.74}, {'flight_id': 'FLT004', 'aircraft_df_type': 'A350', 'origin': 'JFK', 'destination': 'LHR', 'Date': '2025-01-01', 'Take-off Time (UTC)': '08:43', 'CO2_emission': 2348.1}, {'flight_id': 'FLT005', 'aircraft_df_type': 'B777', 'origin': 'DXB', 'destination': 'CDG', 'Date': '2025-01-03', 'Take-off Time (UTC)': '10:03', 'CO2_emission': 2341.51}, {'flight_id': 'FLT006', 'aircraft_df_type': 'A350', 'origin': 'JFK', 'destination': 'DXB', 'Date': '2025-01-16', 'Take-off Time (UTC)': '08:31', 'CO2_emission': 2051.82}, {'flight_id': 'FLT007', 'aircraft_df_type': 'A320', 'origin': 'CDG', 'destination': 'DXB', 'Date': '2025-01-10', 'Take-off Time (UTC)': '06:49', 'CO2_emission': 1963.46}, {'flight_id': 'FLT008', 'aircraft_df_type': 'B737', 'origin': 'CDG', 'destination': 'DXB', 'Date': '2025-01-09', 'Take-off Time (UTC)': '14:51', 'CO2_emission': 2105.18}, {'flight_id': 'FLT009', 'aircraft_df_type': 'A320', 'origin': 'LHR', 'destination': 'DXB', 'Date': '2025-01-09', 'Take-off Time (UTC)': '15:40', 'CO2_emission': 1287.93}]
[2025-05-20T10:07:16.056+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-20T10:07:16.057+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=merge_sources_pipeline, task_id=flight_extraction, run_id=scheduled__2025-04-01T00:00:00+00:00, execution_date=20250401T000000, start_date=20250520T100715, end_date=20250520T100716
[2025-05-20T10:07:16.185+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-20T10:07:16.209+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-05-20T23:03:23.352+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-20T23:03:23.411+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: merge_sources_pipeline.flight_extraction scheduled__2025-04-01T00:00:00+00:00 [queued]>
[2025-05-20T23:03:23.439+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: merge_sources_pipeline.flight_extraction scheduled__2025-04-01T00:00:00+00:00 [queued]>
[2025-05-20T23:03:23.440+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-05-20T23:03:23.472+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): flight_extraction> on 2025-04-01 00:00:00+00:00
[2025-05-20T23:03:23.505+0000] {standard_task_runner.py:72} INFO - Started process 311 to run task
[2025-05-20T23:03:23.516+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'merge_sources_pipeline', 'flight_extraction', 'scheduled__2025-04-01T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/inference_dag.py', '--cfg-path', '/tmp/tmpzusyjeoi']
[2025-05-20T23:03:23.524+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask flight_extraction
[2025-05-20T23:03:23.666+0000] {task_command.py:467} INFO - Running <TaskInstance: merge_sources_pipeline.flight_extraction scheduled__2025-04-01T00:00:00+00:00 [running]> on host 0a7de9743f25
[2025-05-20T23:03:23.885+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='merge_sources_pipeline' AIRFLOW_CTX_TASK_ID='flight_extraction' AIRFLOW_CTX_EXECUTION_DATE='2025-04-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-01T00:00:00+00:00'
[2025-05-20T23:03:23.892+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-20T23:03:23.901+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/inference_dag.py", line 48, in flight_extraction
    flight_df = extract_flight(file_path)
  File "/opt/airflow/scripts/extraction/extract_flight.py", line 14, in extract_flight
    raise FileNotFoundError(f"File not found at : {path}")
FileNotFoundError: File not found at : /opt/***/data/raw_data/flight_2025_04.csv
[2025-05-20T23:03:23.935+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=merge_sources_pipeline, task_id=flight_extraction, run_id=scheduled__2025-04-01T00:00:00+00:00, execution_date=20250401T000000, start_date=20250520T230323, end_date=20250520T230323
[2025-05-20T23:03:24.007+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-20T23:03:24.009+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 11 for task flight_extraction (File not found at : /opt/***/data/raw_data/flight_2025_04.csv; 311)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/inference_dag.py", line 48, in flight_extraction
    flight_df = extract_flight(file_path)
  File "/opt/airflow/scripts/extraction/extract_flight.py", line 14, in extract_flight
    raise FileNotFoundError(f"File not found at : {path}")
FileNotFoundError: File not found at : /opt/***/data/raw_data/flight_2025_04.csv
[2025-05-20T23:03:24.064+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-20T23:03:24.144+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-20T23:03:24.153+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
