[2025-05-21T10:05:25.180+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-21T10:05:25.230+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: merge_sources_pipeline.prediction manual__2025-05-21T09:20:57.597132+00:00 [queued]>
[2025-05-21T10:05:25.251+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: merge_sources_pipeline.prediction manual__2025-05-21T09:20:57.597132+00:00 [queued]>
[2025-05-21T10:05:25.252+0000] {taskinstance.py:2867} INFO - Starting attempt 9 of 9
[2025-05-21T10:05:25.278+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): prediction> on 2025-05-21 09:20:57.597132+00:00
[2025-05-21T10:05:25.300+0000] {standard_task_runner.py:72} INFO - Started process 1428 to run task
[2025-05-21T10:05:25.309+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'merge_sources_pipeline', 'prediction', 'manual__2025-05-21T09:20:57.597132+00:00', '--job-id', '108', '--raw', '--subdir', 'DAGS_FOLDER/inference_dag.py', '--cfg-path', '/tmp/tmp06b48at8']
[2025-05-21T10:05:25.316+0000] {standard_task_runner.py:105} INFO - Job 108: Subtask prediction
[2025-05-21T10:05:25.423+0000] {task_command.py:467} INFO - Running <TaskInstance: merge_sources_pipeline.prediction manual__2025-05-21T09:20:57.597132+00:00 [running]> on host c735ccec6410
[2025-05-21T10:05:25.602+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='merge_sources_pipeline' AIRFLOW_CTX_TASK_ID='prediction' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T09:20:57.597132+00:00' AIRFLOW_CTX_TRY_NUMBER='9' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-21T09:20:57.597132+00:00'
[2025-05-21T10:05:25.605+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-21T10:05:25.652+0000] {logging_mixin.py:190} INFO - Columns in df: []
[2025-05-21T10:05:25.653+0000] {logging_mixin.py:190} INFO - Expected features: ['Aircraft', 'Engine', 'Seats', 'Origin Airport', 'Destination Airport', 'Distance Flown (km)', 'CO2 (kgCO2e)', 'Month', 'Day', 'Weekday', 'Takeoff_Hour']
[2025-05-21T10:05:25.657+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/inference_dag.py", line 95, in prediction
    result_df = run_inference(preprocessed_df)
  File "/opt/airflow/scripts/inference.py", line 16, in run_inference
    y_pred = predictor.predict_contrails(df_predict)
  File "/opt/airflow/scripts/predictor.py", line 37, in predict_contrails
    df=df[self.features] # Align training columns with input data
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 3899, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6115, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6176, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['Aircraft', 'Engine', 'Seats', 'Origin Airport', 'Destination Airport',\n       'Distance Flown (km)', 'CO2 (kgCO2e)', 'Month', 'Day', 'Weekday',\n       'Takeoff_Hour'],\n      dtype='object')] are in the [columns]"
[2025-05-21T10:05:25.684+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=merge_sources_pipeline, task_id=prediction, run_id=manual__2025-05-21T09:20:57.597132+00:00, execution_date=20250521T092057, start_date=20250521T100525, end_date=20250521T100525
[2025-05-21T10:05:25.737+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-21T10:05:25.738+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 108 for task prediction ("None of [Index(['Aircraft', 'Engine', 'Seats', 'Origin Airport', 'Destination Airport',\n       'Distance Flown (km)', 'CO2 (kgCO2e)', 'Month', 'Day', 'Weekday',\n       'Takeoff_Hour'],\n      dtype='object')] are in the [columns]"; 1428)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/inference_dag.py", line 95, in prediction
    result_df = run_inference(preprocessed_df)
  File "/opt/airflow/scripts/inference.py", line 16, in run_inference
    y_pred = predictor.predict_contrails(df_predict)
  File "/opt/airflow/scripts/predictor.py", line 37, in predict_contrails
    df=df[self.features] # Align training columns with input data
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 3899, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6115, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6176, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['Aircraft', 'Engine', 'Seats', 'Origin Airport', 'Destination Airport',\n       'Distance Flown (km)', 'CO2 (kgCO2e)', 'Month', 'Day', 'Weekday',\n       'Takeoff_Hour'],\n      dtype='object')] are in the [columns]"
[2025-05-21T10:05:25.805+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-21T10:05:25.846+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-21T10:05:25.850+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
