[2025-05-21T11:47:09.200+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-21T11:47:09.274+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: contrails_prediction_pipeline.wait_for_flight_file scheduled__2025-04-01T00:00:00+00:00 [queued]>
[2025-05-21T11:47:09.303+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: contrails_prediction_pipeline.wait_for_flight_file scheduled__2025-04-01T00:00:00+00:00 [queued]>
[2025-05-21T11:47:09.304+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-05-21T11:47:09.362+0000] {taskinstance.py:2890} INFO - Executing <Task(FileSensor): wait_for_flight_file> on 2025-04-01 00:00:00+00:00
[2025-05-21T11:47:09.413+0000] {standard_task_runner.py:72} INFO - Started process 123 to run task
[2025-05-21T11:47:09.448+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'contrails_prediction_pipeline', 'wait_for_flight_file', 'scheduled__2025-04-01T00:00:00+00:00', '--job-id', '140', '--raw', '--subdir', 'DAGS_FOLDER/inference_dag.py', '--cfg-path', '/tmp/tmpkw8k2n7d']
[2025-05-21T11:47:09.461+0000] {standard_task_runner.py:105} INFO - Job 140: Subtask wait_for_flight_file
[2025-05-21T11:47:09.671+0000] {task_command.py:467} INFO - Running <TaskInstance: contrails_prediction_pipeline.wait_for_flight_file scheduled__2025-04-01T00:00:00+00:00 [running]> on host 71f2da9c2e69
[2025-05-21T11:47:10.037+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='contrails_prediction_pipeline' AIRFLOW_CTX_TASK_ID='wait_for_flight_file' AIRFLOW_CTX_EXECUTION_DATE='2025-04-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-01T00:00:00+00:00'
[2025-05-21T11:47:10.048+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-21T11:47:10.066+0000] {baseoperator.py:423} WARNING - FileSensor.execute cannot be called outside TaskInstance!
[2025-05-21T11:47:10.146+0000] {base.py:84} INFO - Retrieving connection 'fs_default'
[2025-05-21T11:47:10.151+0000] {filesystem.py:109} INFO - Poking for file /opt/***/data/raw_data/flight_2025_04.csv
[2025-05-21T11:47:10.225+0000] {taskinstance.py:310} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-05-21T11:47:10.226+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-21T11:47:10.301+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-21T11:47:10.536+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-21T11:47:10.550+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-05-21T14:18:19.914+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-21T14:18:20.003+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: contrails_prediction_pipeline.wait_for_flight_file scheduled__2025-04-01T00:00:00+00:00 [queued]>
[2025-05-21T14:18:20.030+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: contrails_prediction_pipeline.wait_for_flight_file scheduled__2025-04-01T00:00:00+00:00 [queued]>
[2025-05-21T14:18:20.032+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-05-21T14:18:20.084+0000] {taskinstance.py:2890} INFO - Executing <Task(FileSensor): wait_for_flight_file> on 2025-04-01 00:00:00+00:00
[2025-05-21T14:18:20.120+0000] {standard_task_runner.py:72} INFO - Started process 112 to run task
[2025-05-21T14:18:20.163+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'contrails_prediction_pipeline', 'wait_for_flight_file', 'scheduled__2025-04-01T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/inference_dag.py', '--cfg-path', '/tmp/tmp3_qfv8cb']
[2025-05-21T14:18:20.193+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask wait_for_flight_file
[2025-05-21T14:18:20.709+0000] {task_command.py:467} INFO - Running <TaskInstance: contrails_prediction_pipeline.wait_for_flight_file scheduled__2025-04-01T00:00:00+00:00 [running]> on host 86ce19bc7751
[2025-05-21T14:18:21.432+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='contrails_prediction_pipeline' AIRFLOW_CTX_TASK_ID='wait_for_flight_file' AIRFLOW_CTX_EXECUTION_DATE='2025-04-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-01T00:00:00+00:00'
[2025-05-21T14:18:21.458+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-21T14:18:21.492+0000] {baseoperator.py:423} WARNING - FileSensor.execute cannot be called outside TaskInstance!
[2025-05-21T14:18:21.621+0000] {base.py:84} INFO - Retrieving connection 'fs_default'
[2025-05-21T14:18:21.636+0000] {filesystem.py:109} INFO - Poking for file /opt/***/data/raw_data/flight_2025_04.csv
[2025-05-21T14:18:21.941+0000] {taskinstance.py:310} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-05-21T14:18:21.944+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-21T14:18:22.064+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-21T14:18:22.324+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-21T14:18:22.344+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
