[2025-05-20T10:07:14.620+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-20T10:07:14.672+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: merge_sources_pipeline.aircraft_extraction scheduled__2025-04-01T00:00:00+00:00 [queued]>
[2025-05-20T10:07:14.698+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: merge_sources_pipeline.aircraft_extraction scheduled__2025-04-01T00:00:00+00:00 [queued]>
[2025-05-20T10:07:14.699+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-05-20T10:07:14.754+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): aircraft_extraction> on 2025-04-01 00:00:00+00:00
[2025-05-20T10:07:14.779+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=173) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-20T10:07:14.790+0000] {standard_task_runner.py:72} INFO - Started process 183 to run task
[2025-05-20T10:07:14.793+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'merge_sources_pipeline', 'aircraft_extraction', 'scheduled__2025-04-01T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/inference_dag.py', '--cfg-path', '/tmp/tmpg5b63b64']
[2025-05-20T10:07:14.804+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask aircraft_extraction
[2025-05-20T10:07:15.012+0000] {task_command.py:467} INFO - Running <TaskInstance: merge_sources_pipeline.aircraft_extraction scheduled__2025-04-01T00:00:00+00:00 [running]> on host f48b776a3d9f
[2025-05-20T10:07:15.786+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='merge_sources_pipeline' AIRFLOW_CTX_TASK_ID='aircraft_extraction' AIRFLOW_CTX_EXECUTION_DATE='2025-04-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-01T00:00:00+00:00'
[2025-05-20T10:07:15.791+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-20T10:07:15.811+0000] {python.py:240} INFO - Done. Returned value was: [{'aircraft_df_type': 'A320', 'engine_model': 'CFM56', 'manufacturer': 'Airbus', 'nb_seats': 180}, {'aircraft_df_type': 'A319', 'engine_model': 'V2500', 'manufacturer': 'Airbus', 'nb_seats': 150}, {'aircraft_df_type': 'B737', 'engine_model': 'CFM56', 'manufacturer': 'Boeing', 'nb_seats': 160}, {'aircraft_df_type': 'B777', 'engine_model': 'GE90', 'manufacturer': 'Boeing', 'nb_seats': 350}, {'aircraft_df_type': 'A350', 'engine_model': 'TRENT900', 'manufacturer': 'Airbus', 'nb_seats': 300}, {'aircraft_df_type': 'A380', 'engine_model': 'TRENT900', 'manufacturer': 'Airbus', 'nb_seats': 550}, {'aircraft_df_type': 'B787', 'engine_model': 'GENX', 'manufacturer': 'Boeing', 'nb_seats': 280}, {'aircraft_df_type': 'E190', 'engine_model': 'CF34', 'manufacturer': 'Embraer', 'nb_seats': 100}]
[2025-05-20T10:07:15.880+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-20T10:07:15.881+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=merge_sources_pipeline, task_id=aircraft_extraction, run_id=scheduled__2025-04-01T00:00:00+00:00, execution_date=20250401T000000, start_date=20250520T100714, end_date=20250520T100715
[2025-05-20T10:07:15.988+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-20T10:07:16.074+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-20T10:07:16.082+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-05-20T23:03:23.476+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-20T23:03:23.531+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: merge_sources_pipeline.aircraft_extraction scheduled__2025-04-01T00:00:00+00:00 [queued]>
[2025-05-20T23:03:23.554+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: merge_sources_pipeline.aircraft_extraction scheduled__2025-04-01T00:00:00+00:00 [queued]>
[2025-05-20T23:03:23.555+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-05-20T23:03:23.584+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): aircraft_extraction> on 2025-04-01 00:00:00+00:00
[2025-05-20T23:03:23.607+0000] {standard_task_runner.py:72} INFO - Started process 313 to run task
[2025-05-20T23:03:23.626+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'merge_sources_pipeline', 'aircraft_extraction', 'scheduled__2025-04-01T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/inference_dag.py', '--cfg-path', '/tmp/tmptcb30jjx']
[2025-05-20T23:03:23.639+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask aircraft_extraction
[2025-05-20T23:03:23.794+0000] {task_command.py:467} INFO - Running <TaskInstance: merge_sources_pipeline.aircraft_extraction scheduled__2025-04-01T00:00:00+00:00 [running]> on host 0a7de9743f25
[2025-05-20T23:03:24.005+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='merge_sources_pipeline' AIRFLOW_CTX_TASK_ID='aircraft_extraction' AIRFLOW_CTX_EXECUTION_DATE='2025-04-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-01T00:00:00+00:00'
[2025-05-20T23:03:24.009+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-20T23:03:24.017+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/inference_dag.py", line 41, in aircraft_extraction
    aircraft_df = extract_aircraft(file_path)
  File "/opt/airflow/scripts/extraction/extract_aircraft.py", line 16, in extract_aircraft
    raise FileNotFoundError(f"File not found at : {path}")
FileNotFoundError: File not found at : /opt/***/data/raw_data/aircraft_2025_04.csv
[2025-05-20T23:03:24.043+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=merge_sources_pipeline, task_id=aircraft_extraction, run_id=scheduled__2025-04-01T00:00:00+00:00, execution_date=20250401T000000, start_date=20250520T230323, end_date=20250520T230324
[2025-05-20T23:03:24.101+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-20T23:03:24.102+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 12 for task aircraft_extraction (File not found at : /opt/***/data/raw_data/aircraft_2025_04.csv; 313)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/inference_dag.py", line 41, in aircraft_extraction
    aircraft_df = extract_aircraft(file_path)
  File "/opt/airflow/scripts/extraction/extract_aircraft.py", line 16, in extract_aircraft
    raise FileNotFoundError(f"File not found at : {path}")
FileNotFoundError: File not found at : /opt/***/data/raw_data/aircraft_2025_04.csv
[2025-05-20T23:03:24.176+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-20T23:03:24.236+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-20T23:03:24.244+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
