[2025-05-21T08:40:00.784+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-21T08:40:00.884+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: merge_sources_pipeline.wait_for_airport_update manual__2025-05-21T08:39:51.651181+00:00 [queued]>
[2025-05-21T08:40:00.907+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: merge_sources_pipeline.wait_for_airport_update manual__2025-05-21T08:39:51.651181+00:00 [queued]>
[2025-05-21T08:40:00.908+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-05-21T08:40:00.948+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): wait_for_airport_update> on 2025-05-21 08:39:51.651181+00:00
[2025-05-21T08:40:00.982+0000] {standard_task_runner.py:72} INFO - Started process 144 to run task
[2025-05-21T08:40:01.000+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'merge_sources_pipeline', 'wait_for_airport_update', 'manual__2025-05-21T08:39:51.651181+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/inference_dag.py', '--cfg-path', '/tmp/tmp6wqizpkt']
[2025-05-21T08:40:01.016+0000] {standard_task_runner.py:105} INFO - Job 79: Subtask wait_for_airport_update
[2025-05-21T08:40:01.192+0000] {task_command.py:467} INFO - Running <TaskInstance: merge_sources_pipeline.wait_for_airport_update manual__2025-05-21T08:39:51.651181+00:00 [running]> on host c735ccec6410
[2025-05-21T08:40:01.375+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='merge_sources_pipeline' AIRFLOW_CTX_TASK_ID='wait_for_airport_update' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T08:39:51.651181+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-21T08:39:51.651181+00:00'
[2025-05-21T08:40:01.381+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-21T08:40:01.625+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/inference_dag.py", line 55, in wait_for_airport_update
    raise ValueError(f"Airports data too old: last modified at {last_mod}, expected at least {execution_date}")
ValueError: Airports data too old: last modified at 2025-05-21 01:53:11+00:00, expected at least 2025-05-21 08:39:51.651181+00:00
[2025-05-21T08:40:01.661+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=merge_sources_pipeline, task_id=wait_for_airport_update, run_id=manual__2025-05-21T08:39:51.651181+00:00, execution_date=20250521T083951, start_date=20250521T084000, end_date=20250521T084001
[2025-05-21T08:40:01.754+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-21T08:40:01.755+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 79 for task wait_for_airport_update (Airports data too old: last modified at 2025-05-21 01:53:11+00:00, expected at least 2025-05-21 08:39:51.651181+00:00; 144)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/inference_dag.py", line 55, in wait_for_airport_update
    raise ValueError(f"Airports data too old: last modified at {last_mod}, expected at least {execution_date}")
ValueError: Airports data too old: last modified at 2025-05-21 01:53:11+00:00, expected at least 2025-05-21 08:39:51.651181+00:00
[2025-05-21T08:40:01.819+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-21T08:40:01.868+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-21T08:40:01.872+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
